GHA: fix covr

diff --git a/.github/workflows/test-coverage.yaml b/.github/workflows/test-coverage.yaml
--- a/.github/workflows/test-coverage.yaml
+++ b/.github/workflows/test-coverage.yaml
@@ -1,39 +1,24 @@
 on: [push]
 
-name: covr
+name: test-coverage.yaml
+
+permissions: read-all
 
 jobs:
-  covr:
-    if: "! contains(github.event.head_commit.message, '[ci skip]')"    
-
-    timeout-minutes: 45
-
+  test-coverage:
     runs-on: ubuntu-latest
-
-    name: covr
-
-    strategy:
-      fail-fast: false
-
     env:
       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
-      R_KEEP_PKG_SOURCE: yes
-      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
-      ## Test in other locale (optional)
-      LANGUAGE: ${{ matrix.config.language }}
-      ## R CMD check
-      _R_CHECK_CRAN_INCOMING_: false
-      _R_CHECK_LENGTH_1_CONDITION_: true
-      _R_CHECK_LENGTH_1_LOGIC2_: true
-      _R_CHECK_MATRIX_DATA_: true
-      _R_CHECK_SUGGESTS_ONLY_: true
-      _R_CHECK_THINGS_IN_TEMP_DIR_: true
-      RCMDCHECK_ERROR_ON: note
-      ## Specific to futures
-      R_FUTURE_RNG_ONMISUSE: error
 
     steps:
       - uses: actions/checkout@v4
+
+      - name: Assert CODECOV_TOKEN is set
+        run: |
+          if [[ -z "${{secrets.CODECOV_TOKEN}}" ]]; then
+            >&2 echo "::error::ERROR: 'secrets.CODECOV_TOKEN' not set"
+            exit 1
+          fi
 
       - uses: r-lib/actions/setup-r@v2
         with:
@@ -42,32 +27,41 @@ jobs:
       - uses: r-lib/actions/setup-r-dependencies@v2
         with:
           extra-packages: |
-            any::rcmdcheck
-            any::remotes
-            any::sessioninfo
             any::covr
-          needs: check
+            any::xml2
+            any::remotes
+          needs: coverage
 
-      - name: Install dependencies
+      - name: Install package itself (special case)
         run: |
-          remotes::install_deps(dependencies = TRUE)
-          install.packages(".", repos=NULL, type="source")
+          if (packageVersion("future") <= "1.34.0") {
+            remotes::install_github("futureverse/future", ref = "feature/FutureBackend")
+          }
+          install.packages(".", repos = NULL, type = "source")
         shell: Rscript {0}
 
-      - name: Session info
-        run: |
-          options(width = 100)
-          pkgs <- installed.packages()[, "Package"]
-          sessioninfo::session_info(pkgs, include_base = TRUE)
-        shell: Rscript {0}
-    
       - name: Test coverage
         run: |
-          ## 1. Get 'Repository Upload Token' from Codecov:
-          ##    https://app.codecov.io/gh/<org>/<repo>/settings
-          ## 2. Set 'CODECOV_TOKEN' in GitHub Secrets:
-          ##    https://github.com/<org>/<repo>/settings/environments/
-          coverage <- covr::package_coverage(quiet = FALSE)
-          print(coverage)
-          covr::codecov(coverage = coverage, token="${{secrets.CODECOV_TOKEN}}")
+          cov <- covr::package_coverage(
+            quiet = FALSE,
+            clean = FALSE,
+            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
+          )
+          print(cov)
+          covr::to_cobertura(cov)
         shell: Rscript {0}
+
+      - uses: codecov/codecov-action@v4
+        with:
+          fail_ci_if_error: ${{ github.event_name != 'pull_request' && true || false }}
+          file: ./cobertura.xml
+          plugin: noop
+          disable_search: true
+          token: ${{ secrets.CODECOV_TOKEN }}
+
+      - name: Upload test results
+        if: failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: coverage-test-failures
+          path: ${{ runner.temp }}/package
